### PR TITLE
chore(imagemin): Lock dependency

### LINKED ISSUE #99: Bug in imagemin 5.3.0
Looks like there's an issue with the latest release of imagemin - would it be possible to lock the version to v5.2.2 until this is resolved?

https://github.com/imagemin/imagemin/issues/243

### PR DESCRIPTION
**Pull request by obartra**
Lock image min dependency until https://github.com/imagemin/imagemin/issues/243 is resolved

Closes #99

### CODE REVIEW

**Comment by tcoopman** [comment]
It looks like this bug is already fixed, can you confirm and if confirmed, please close the PR.
Thanks

**Comment by obartra** [comment]
It's up to you, the bug is fixed so we can close it but it may also be worth locking not just imagemin but all dependencies.

I'm happy to update the PR to add that. That way these issues won't happen again and will only update when you manually do it. This should help prevent regressions caused by other libraries.

**Comment by obartra** [comment]
Closing for now, feel free to reopen if this is a desired feature

**Comment by tcoopman** [comment]
I would like to see a bit more discussion on this. If more users want to have the deps locked, I'm fine for it. Feel free to open a bug to start the discussion.

**Pull request closed without merging**
