### PR TITLE
Added a way to manually add Optimizers (Plugins)

### PR DESCRIPTION
**Pull request by Milewski**
For example

```
{
    loader: 'image-webpack-loader',
    query: {
        plugins: {
            guetzli: require('imagemin-guetzli')
        },
        guetzli: {
            quality: 90
        }
    }
}
```

the **key** used in the plugins object will become the **key** on the configuration

### CODE REVIEW

**Comment by tcoopman** [comment]
Can you update the readme with a clear example of how to use this and why you would want to use it.

**Comment by Milewski** [comment]
Done... its pretty-much allow anyone to send a function as plugin...

however ultimately i think it would be better if there was no bundled plugin at all.. as for example one might be using pngquant but not gifsicle.. or moz.. or others and still get to have the dependencies installed into their system...  what could be done to address this issue could be check if the plugin is installed... if not console.warn('you need to npm install imagemin-mozjpeg') if there was an attempt to use it

**Comment by jamesmfriedman** [comment]
Not sure if this was going to get merged in, but I would definitely use it.

I want to use the imagemin png to jpeg converter and also use Google's Guetzli jpeg optimizer. This seems like what I'd need.

I'll use the fork for now, thanks for good the work :)

**Comment by milewski** [comment]
@jamesmfriedman i actually made a version which doesnt come bundled with any plugin.. you can install just the ones you need manually ... heads on here https://github.com/milewski/imagemin-loader

**Pull request closed without merging**
