### PR TITLE
Allow options for all optimizers

### PR DESCRIPTION
**Pull request by TomDeBacker**

### CODE REVIEW

**Comment by daltones** [comment]
Notice that although the new way of passing options to `gifsicle` and `optipng` seems better, that's technically a _breaking change_.

It should continue to support options `interlaced` and `optimizationLevel` with a deprecation warning.

**Comment by TomDeBacker** [comment]
@tcoopman What do you think about supporting the old options? I'm fine with making a new PR for this.

**Comment by tcoopman** [comment]
@TomDeBacker you're right. I missed those, so it should have been a breaking change. If you can fix it please.

**Comment by TomDeBacker** [comment]
[PR #58 ](https://github.com/tcoopman/image-webpack-loader/pull/58)

**Pull request merged**
