### PR TITLE
fix(webpack2): handle case in which no loader options are provided

### PR DESCRIPTION
**Pull request by fpipita**
This PR fixes the case in which `loaderUtils.getOptions()` returns null. 

Check https://github.com/webpack/loader-utils#getoptions for more information.

### CODE REVIEW

**Comment by VitorLuizC** [comment]
When it will be published? #88, #89 and #90 is related to the issue fixed on this.

**Comment by tquetano-r7** [comment]
So ... this is still totally an issue, can no one publish this?

**Comment by tcoopman** [comment]
sorry, I thought I already published this, will do it later today

**Comment by tquetano-r7** [comment]
thanks bud, much obliged

**Comment by tcoopman** [comment]
published as 3.3.1

**Comment by tquetano-r7** [comment]
Confirmed! Works as expected. :man_dancing:

**Pull request merged**
