### PR TITLE
Updating webpack-cli to 2.1.5

### PR DESCRIPTION
**Pull request by tirthbodawala**

### CODE REVIEW

**Comment by tcoopman** [comment]
This is not really needed, is it? The `^` will take the latest allowed version when you install it?

**Comment by hal869** [comment]
@tirthbodawala @tcoopman 

webpack-cli has deps on jscodeshift, which despite numerous requests/PRs to the the devs there, is not getting updated deps on nomnom & babel@6.  especially for those using @babel^7, installing webpack-cli forces the install of babel@6.  it's a mess.

webpack project provides an alternative option to webpack-cli, namely, webpack-command (https://webpack.js.org/api/cli/)

for those interested in / preffering webback-command, is it necessary to force even a --dev dependency on webpack-cli here?

can it be made conditional?

**Comment by tcoopman** [comment]
@hal869 that sounds like something for a different PR? Can you take a stab at it?

**Comment by hal869** [comment]
@tcoopman 

just commented *here* as the req't is being _set_ here.

as for *how* to implement a conditional reqt in package.json, no idea.  will take a look around ...

**Comment by tcoopman** [comment]
I've merged this with #165

**Pull request closed without merging**
