### PR TITLE
Update Webpack 2 syntax (query -> options)

### PR DESCRIPTION
**Pull request by davidcalhoun**
See https://webpack.js.org/configuration/module/#rule-options-rule-query

### CODE REVIEW

**Comment by tcoopman** [comment]
Is this a backwards compatible change?

**Comment by davidcalhoun** [comment]
From testing with Webpack 2.1.0-beta.26, it looks like `query` didn't work at all.  Not sure about previous versions of Webpack 2.

**Comment by tcoopman** [comment]
But does this new syntax work with webpack 1?

**Comment by davidcalhoun** [comment]
Oh sorry I misunderstood.  No, it won't work with Webpack 1, so it should be explicit that this is just for Webpack 2.  The current comment above this changed code block should be good enough :)

`With webpack 2 now supporting query object syntax, you can also write as`

**Comment by davidcalhoun** [comment]
Doh, just realized that that comment above the code block probably needs to be changed as well, since refers to `query`

**Comment by seanes** [comment]
Any update on this? Any plans to release e.g. a new major supporting WebPack 2.x and on?

**Comment by kud** [comment]
https://github.com/tcoopman/image-webpack-loader/pull/91

**Comment by kud** [comment]
Mine's better as I also changed the options which can't be global anymore. :p

**Pull request closed without merging**
