### PR TITLE
Added back in jpegtran

### LINKED ISSUE #80: Stripping EXIF Data
With the switch from jpegtran to mozjpeg there the ability to strip EXIF data was lost, can we include both? Even if jpegtran is disabed by default

### PR DESCRIPTION
**Pull request by leonsmith**
Fixes #80 

No obligation to take this PR
Would be interesting to discuss making the processors pluggable?

### CODE REVIEW

**Comment by dkrnl** [comment]
Good work! wait merge ...

**Comment by tcoopman** [comment]
It seems I've lost sight of this PR. Maybe it's indeed a good idea to make the processors pluggable. What would be the best options for this kind of work. Does anyone have experience or good examples for this?

**Comment by dkrnl** [comment]
@tcoopman, For example, i`m not use jpeg resize (or other processing), but use only jpegtran for strip EXIF.
Pluggable processors its good idea, if only one jpeg-proccessor enabled by default.

**Comment by tcoopman** [comment]
@dkrnl I'm mostly thinking about how this should work. Should we do it like babel/eslint where you have to define plugins in the config?
I would like this to be easy to use, so it shouldn't be hard to add an other processor.

**Comment by dkrnl** [comment]
Now i use custom webpack loader, idea from [postcss-loader](https://github.com/postcss/postcss-loader#plugins).

In webpack.config.js:
```js
            {
                test: /\.(jpe?g|png|gif|svg)$/i,
                exclude: /fonts/,
                loaders: [
                    {
                        loader: 'file-loader',
                        options: {
                            name: 'img/[name].[ext]?[hash]',
                        },
                    },
                    {
                        loader: path.join(__dirname, 'imagemin.loader.js'),
                        options: {
                            plugins: [
                                require('imagemin-jpegtran')({
                                    // https://github.com/imagemin/imagemin-jpegtran
                                }),
                                require('imagemin-svgo')({
                                    // https://github.com/imagemin/imagemin-svgo
                                }),
                                require('imagemin-pngquant')({
                                    // https://github.com/imagemin/imagemin-pngquant
                                }),
                            ],
                        },
                    },
                ],
            },
```
In imagemin.loader.js:
```js
const path = require('path');
const imagemin = require('imagemin');
const loaderUtils = require('loader-utils');

module.exports = function imageminLoader(content) {
    this.cacheable && this.cacheable();

    const callback = this.async();
    const plugins = loaderUtils.getOptions(this).plugins;
    const resourcePath = path.relative(__dirname, this.resourcePath);

    imagemin.buffer(content, {
        plugins,
    }).then((data) => {
        let delta = data.length - content.length;
        if (delta > 0) {
            this.emitWarning(`Imagemin NOT processed: ${resourcePath} \t +${delta} bytes`);
            callback(null, content);
        } else {
            console.log(`Imagemin processed: ${resourcePath} \t ${delta} bytes`);
            callback(null, data);
        }
    }).catch((err) => {
        console.log(`Imagemin error: ${resourcePath}`);
        callback(err);
    });
};

module.exports.raw = true;
```

**Pull request closed without merging**
