### PR TITLE
Clean docs

### PR DESCRIPTION
**Pull request by Zephir77167**
Listing options was tedious, the list wasn't exhaustive and could easily get out of date

Also, Webpack 2 has been out for a while and the v1 syntax could confuse users.

I think the new version is cleaner and more approachable by newcomers, but let me know what you think!

### CODE REVIEW

**Comment by DanielRuf** [comment]
lgtm

**Comment by DanielRuf** [comment]
Hm, but shouldn't it be `module - rules` instead of `loaders`?

**Comment by DanielRuf** [comment]
Shouldn't we use `rules` instead of `loaders` https://stackoverflow.com/a/43805263/753676

https://webpack.js.org/guides/migrating/#module-loaders-is-now-module-rules

**Comment by DanielRuf** [comment]
I miss the regular expression part for webp.

**Comment by tcoopman** [comment]
Going to merge this improvement already, thanks! @DanielRuf if you want you can submit a new PR to further improve the documentation.

Thanks!

**Comment by Zephir77167** [comment]
@DanielRuf You are right, I will fix it :) Thanks for feedback!

**Pull request merged**
