### PR TITLE
Fix webp problem

### PR DESCRIPTION
**Pull request by fearintino**
Make using webp optionable

### CODE REVIEW

**Comment by Zephir77167** [comment]
Hi, this is the result of a merge problem. The code that should have been left out is the one on top of the one you deleted. I will open a PR. Again, sorry for the inconvenience

**Comment by Zephir77167** [comment]
https://github.com/tcoopman/image-webpack-loader/pull/115

**Comment by fearintino** [comment]
It seems that you again make it always enabled. Because if(options.webp) will be always true.

**Comment by Zephir77167** [comment]
#115 now works as intended

**Comment by tcoopman** [comment]
Merged #115

**Pull request closed without merging**
